const data = {
    "first_name": "Yuliia",
    "last_name": "Kyivska",
    "job_title": "Full Stuck Developer",
    "photo": "./images/w1.jpg",
    "adressphone": "+380993106338",
    "phone": "+38 (099) 310 63 38",
    "email": "kiev.lia@gmail.com",
    "skype": "skype: Yuliia Kyivska",
    "adresskype": `live:.cid.544ae9f7314f9a59`,
    "linkedin": "linkedin: Yuliia Kyivska",
    "addresslinkedin": `https://www.linkedin.com/in/yuliia-kyivska-925a9353/`,
    "address": "Ukraine, Vinnitsa",
    "skills": [
        "HTML",
        "Cascading Style Sheets (CSS)",
        "JavaScript",
        "Node.js",
        "Bootstrap",
        "Git",
        "Project Management",
        "Contact Negotiation",
        "Ad Buying & Planning",
        "Product Positioning",
        "Visual Merchandising",
        "Search Engine Ads",
        "Process Improvement",
        "Market Strategizing",
        "Organic Search",
        "Technical Writing",
        "Google Web Analytics",
        "Fluent in English",
    ],
    "education": [
        ["2000-2004", "V. N. Karazin Kharkiv National University, Bachelor of Computational and Applied Mathematics degree"],
        ["2004-2005", "V. N. Karazin Kharkiv National University, Master's Degree in Computational and Applied Mathematics"],
    ],
    "achievements": [
        "SEO Analyst 2010-2019",
        "Front-end developer",
        "web-developer" 
    ],
    "profile": "Now I can devote myself to the new profession of Developer. I know CSS, HTML, JS. Also, I will lern mastered React. I have been coding for 7 months and during this time I have done 1 successful team projects as TeamLead and 2 individual ones. I have hands-on experience in following Agile /Scrum methodology when working in a team. My strenghts are: I am an excellent analyst, a quick learner and I have communication skills. Bringing benefit world, the opportunity to communicate with the different piple and feel free, what could be more beautiful than this?"
};